FROM php:8.4-alpine

WORKDIR /var/www/html

RUN curl -sLS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer

COPY . .

RUN composer install \
    && rm -fr .cache
#  remove the trivy testing vulnerability tools cache

CMD [ "echo", "Hello, world" ]